<?php

namespace orangins\modules\people\engine;

use orangins\modules\people\menuitem\PhabricatorPeopleDetailsProfileMenuItem;
use orangins\modules\people\menuitem\PhabricatorPeopleManageProfileMenuItem;
use orangins\modules\people\menuitem\PhabricatorPeoplePictureProfileMenuItem;
use orangins\modules\search\engine\PhabricatorProfileMenuEngine;
use yii\helpers\ArrayHelper;
use yii\helpers\Url;

/**
 * Class PhabricatorPeopleProfileMenuEngine
 * @package orangins\modules\people\engine
 * @author 陈妙威
 */
final class PhabricatorPeopleProfileMenuEngine
    extends PhabricatorProfileMenuEngine
{

    /**
     *
     */
    const ITEM_PROFILE = 'people.profile';

    /**
     * @return string
     * @author 陈妙威
     */
    public static function className()
    {
        return parent::className(); // TODO: Change the autogenerated stub
    }

    /**
     *
     */
    const ITEM_MANAGE = 'people.manage';
    /**
     *
     */
    const ITEM_PICTURE = 'people.picture';
    /**
     *
     */
    const ITEM_BADGES = 'people.badges';
    /**
     *
     */
    const ITEM_TASKS = 'people.tasks';
    /**
     *
     */
    const ITEM_COMMITS = 'people.commits';
    /**
     *
     */
    const ITEM_REVISIONS = 'people.revisions';

    /**
     * @return bool|mixed
     * @author 陈妙威
     */
    protected function isMenuEngineConfigurable()
    {
        return false;
    }

    /**
     * @param $params
     * @return mixed|string
     * @author 陈妙威
     */
    public function getItemURI($params)
    {
        $user = $this->getProfileObject();
        return Url::to(ArrayHelper::merge(['/people/index/item', 'id' => $user->getID()], $params));
    }

    /**
     * @param $object
     * @return array|\orangins\modules\search\models\PhabricatorProfileMenuItemConfiguration[]
     * @author 陈妙威
     */
    protected function getBuiltinProfileItems($object)
    {
        $viewer = $this->getViewer();

        $items = array();

        $items[] = $this->newItem()
            ->setBuiltinKey(self::ITEM_PICTURE)
            ->setMenuItemKey(PhabricatorPeoplePictureProfileMenuItem::MENUITEMKEY);

        $items[] = $this->newItem()
            ->setBuiltinKey(self::ITEM_PROFILE)
            ->setMenuItemKey(PhabricatorPeopleDetailsProfileMenuItem::MENUITEMKEY);


        $items[] = $this->newItem()
            ->setBuiltinKey(self::ITEM_MANAGE)
            ->setMenuItemKey(PhabricatorPeopleManageProfileMenuItem::MENUITEMKEY);

        return $items;
    }

}
