<?php

namespace orangins\lib\infrastructure\contentsource;

/**
 * Class PhabricatorConsoleContentSource
 * @package orangins\lib\infrastructure\contentsource
 * @author 陈妙威
 */
final class PhabricatorConsoleContentSource
    extends PhabricatorContentSource
{

    /**
     *
     */
    const SOURCECONST = 'console';

    /**
     * @return mixed|string
     * @author 陈妙威
     */
    public function getSourceName()
    {
        return pht('Console');
    }

    /**
     * @return mixed|string
     * @author 陈妙威
     */
    public function getSourceDescription()
    {
        return pht('Content generated by CLI administrative tools.');
    }

}
