<?php
/**
 * Created by PhpStorm.
 * User: air
 * Date: 2018/8/21
 * Time: 11:33 PM
 */

namespace orangins\modules\widgets\assets;


/**
 * Class FormSelect2Asset
 * @package orangins\modules\widgets\assets
 */
class FormSelect2Asset extends AssetBundle
{
    /**
     * @var array
     */
    public $css = [
    ];
    /**
     * @var array
     */
    public $js = [
        'global/js/demo_pages/form_select2.js',
    ];
    /**
     * @var array
     */
    public $depends = [
        'orangins\modules\widgets\assets\ResourceAsset',
    ];

    /**
     *
     */
    public function init()
    {
        $this->sourcePath = __DIR__ . "/resource";
        parent::init(); // TODO: Change the autogenerated stub
    }
}